language: swift
os: osx
osx_image: xcode10.2

language: swift
osx_image: xcode10.2
install: brew install danger/tap/danger-swift
xcode_project: BankStatement.xcodeproj
xcode_scheme: BankStatement
- script: danger-swift ci
- script: xcodebuild clean build test -project BankStatement.xcodeproj -scheme BankStatement ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO   CODE_SIGN_IDENTITY=""


# prepare dependency managers
before_install:
  - brew update
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
# install dependencies
install:
  - bundle install
# jobs and stages to run
jobs:
  include:
    - stage: "Code validation"
      name: "Code validation"
      script:
        - bundle exec danger
